Feature/32
TeHikuMedia/DeepSpeech pull request #14
Opened 2021-04-27 01:48 UTC by ki-arie

Lot's to unpack here.

Happy for code walkthrough before the merge.

2021-05-03 03:04 UTC, ki-arie commented on native_client/modelstate.cc
> -        static_cast<float>(std::exp(out[i].probabilities[j]))          // probability
FYI @utunga this is the line where we add an extra exp to the logit`static_cast<float>(std::exp(out[i].probabilities[j]))`.

I'm taking it out atm, but we will add it using another ticket/feature, just to make sure it's the only functionality we're testing/adding

2021-05-04 05:18 UTC, ki-arie commented on native_client/modelstate.cc
> -        static_cast<float>(std::exp(out[i].probabilities[j]))          // probability
Oh man, just realized this PR overwrite some changes you did on the API, I'll correct this up tmr

2021-05-04 08:48 UTC, utunga commented
Just a quick comment on status of where I'm at.. have most of the tooling installed I think but with bazel 3.1.0 set as default and a clean check out feature/32 and submodules etc I am currently getting this 

<img width="784" alt="image" src="https://user-images.githubusercontent.com/166867/116980000-cd97d700-ad19-11eb-8efb-ef510a22c24e.png">

`INFO: From Linking external/ruy/ruy/profiler/libinstrumentation.a:
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for library: bazel-out/darwin-opt/bin/external/ruy/ruy/profiler/libinstrumentation.a the table of contents is empty (no object file members in the library define global symbols)
ERROR: /Users/utunga/papa/DeepSpeech/tensorflow/native_client/BUILD:114:1: C++ compilation of rule '//native_client:sentencefit_bundle' failed (Exit 1)
native_client/sentencefit.cc:7:10: fatal error: 'xtensor/xarray.hpp' file not found
#include "xtensor/xarray.hpp"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.`

On this occasion I chose all defaults when running ./configure in tensorflow dir (which includes not enabling suport for iOS)

2021-05-04 09:07 UTC, utunga commented
PS. I used `git pull --recurse-submodules
`
And it was not succesful 

So then.I tried 
`git submodule update --init --recursive`

And it was super effective. 

Also, forget the ./configure step. I guess that's not needed. 

PS I guess the problem is that I did 
git clone --recursive 

but then I checked out the branch and it didn't update the submodules. Even, as I say after git pull --recurse. But yeah the other one was the go, it seems.

2021-05-04 23:01 UTC, utunga requested changes
OK so we were going to add that tiny bit of print data and then just verify that we're getting probability metadata in a/the test

2021-05-04 23:01 UTC, utunga commented on native_client/modelstate.cc
> -        static_cast<float>(std::exp(out[i].probabilities[j]))          // probability
Hmm.. on further consideration, I dunno. 

Taking it out completely is a breaking change.

Leaving it with ```std::exp()``` is (almost certainly) incorrect.

Given that by far the bulk of the hassle here is the whole business of building and tagging the binaries and getting them deployed I'm erring on the side of suggesting we just put it (back) to ... 

```
static_cast<float>(out[i].probabilities[j]) // probability
```

That way the per char metadata will at least be there. We can still treat it as a separate task to decide if this actually helps or hinders matters.

2021-05-04 23:01 UTC, utunga commented on native_client/python/impl.i
>    def __repr__(self):
request that we add the prob to the default print output

2021-05-04 23:04 UTC, utunga requested changes
Eek sorry doing this again.. not sure if this will show up twice now. 

Requested changes
-- Add probablity to impl.i print output for Metadata
-- Remove the exp() around probability in the output step (do'h) 
-- Verify that we're getting metadata in the test

2021-05-04 23:53 UTC, utunga commented on native_client/python/make_test_python.sh
> +pip install dist/*.whl
👍

2021-05-05 02:01 UTC, utunga approved these changes
AWESOME 

WFM

2021-05-05 03:02 UTC, merged